# $schema: https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json

services:
  iperf3:
    restart: unless-stopped
    container_name: iperf3-server
    image: tangentsoft/iperf3:v3.19
    ports:
      - 5201:5201/udp
      - 5201:5201/tcp
