# $schema: https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json

services:

  cloudflared:
    image: cloudflare/cloudflared:2026.1.2
    container_name: cloudflared
    command: --config /etc/cloudflared/config.yml tunnel run
    user: 568:568
    configs:
      - source: cloudflared
        target: /etc/cloudflared/config.yml
        uid: "568"
        gid: "568"
        mode: 0440
    volumes:
      - /mnt/spool/apps/config/cloudflared:/etc/cloudflared
    networks:
      - cloudflare
    restart: unless-stopped

  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget:release-25.4
    env_file:
      - stack.env
    volumes:
      - /mnt/spool/apps/config/nzbget:/config
      - /mnt/dpool/media:/media
    expose:
      - "6789"
    networks:
      - cloudflare
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.3.0.5236
    container_name: prowlarr
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /mnt/spool/apps/config/prowlarr:/config
      - /mnt/dpool/media:/media
    expose:
      - "9696"
    depends_on:
      - byparr
    networks:
      - cloudflare

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    env_file:
      - stack.env
    expose:
      - "8191"
    networks:
      - cloudflare
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:release-6.0.4.10291
    container_name: radarr
    env_file:
      - stack.env
    volumes:
      - /mnt/spool/apps/config/radarr:/config
      - /mnt/dpool/media:/media
    expose:
      - "7878"
    depends_on:
      - prowlarr
    networks:
      - cloudflare
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.16.2944
    container_name: sonarr
    env_file:
      - stack.env
    volumes:
      - /mnt/spool/apps/config/sonarr:/config
      - /mnt/dpool/media:/media
    expose:
      - "8989"
    depends_on:
      - prowlarr
    networks:
      - cloudflare
    restart: unless-stopped

  unpackerr:
    image: ghcr.io/hotio/unpackerr:release-0.14.5
    container_name: unpackerr
    env_file:
      - stack.env
    volumes:
      - /mnt/spool/apps/config/unpackerr:/config
      - /mnt/dpool/media:/media
    depends_on:
      - radarr
      - sonarr
    networks:
      - cloudflare
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.5.2
    container_name: recyclarr
    user: 1000:1000
    env_file:
      - stack.env
    environment:
      - CRON_SCHEDULE=@daily
    volumes:
      - /mnt/spool/apps/config/recyclarr:/config:ro
    depends_on:
      - radarr
      - sonarr
    networks:
      - cloudflare
    restart: unless-stopped

configs:
  cloudflared:
    content: |
      tunnel: 08942756-aeb6-45dc-aaaa-5ff4ee5a0475
      credentials-file: /etc/cloudflared/creds/08942756-aeb6-45dc-aaaa-5ff4ee5a0475.json
      ingress:
        - hostname: media-prowlarr.alekseev.us
          service: http://prowlarr:9696
          access:
            required: true
            teamName: alekseev
            audTag:
              - 28301c1e32ae3464a9017afc913e4770a0092631d412ad8144395add357c87c5
        - hostname: media-radarr.alekseev.us
          service: http://radarr:7878
          access:
            required: true
            teamName: alekseev
            audTag:
              - 6907f3d06f86c26e1fb7b26b75470ac1aa3f8b6cd60ba8df7b370fe8406669e9
        - hostname: media-sonarr.alekseev.us
          service: http://sonarr:8989
          access:
            required: true
            teamName: alekseev
            audTag:
              - 00d9b88538ea4d3f73429e864dc9a163ae0199d6224fb1c2550de2c869f9885d
        - hostname: nzbget.alekseev.us
          service: http://nzbget:6789
        - service: http_status:404

networks:
  cloudflare:
    name: cloudflare
