services:
  plex:
    image: plexinc/pms-docker:1.42.1.10060-4e8b05daf
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # Change this to match your server's timezone
      #- PLEX_CLAIM= # Uncomment this to setup Plex server, get your claim code from here - https://www.plex.tv/claim/
      # Uncomment the lines below to use Nvidia GPUs for Hardware Transcoding
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/spool/apps/config/plex:/config
      # Uncomment the lines below for each library,
      # make sure the path on the left of the colon (:) exists on the host! `/mnt/tv`
      #- /mnt/tv:/mnt/tv
      #- /mnt/movies:/mnt/movies
      #- /mnt/music:/mnt/music
      #- /mnt/transcode:/mnt/transcode
      - /mnt/dpool/media:/media
    restart: unless-stopped
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
    network_mode: host
